

const products = [
  { id: 1,  name: "Anting Fashion", category: "Aksesori", price: 90000, img: "Anting Fashion.jpg" },
  { id: 2,  name: "Blazer Slim Fit", category: "Outerwear", price: 120000, img: "Blazer Slim Fit.jpg" },
  { id: 3,  name: "Blouse Lengan Puff", category: "Atasan", price: 100000, img: "Blouse Lengan Puff.jpg" },
  { id: 4,  name: "Bomber Jacket", category: "Outerwear", price: 120000, img: "Bomber Jacket.jpg" },
  { id: 5,  name: "Boots Kulit", category: "Footwear", price: 130000, img: "Boots Kulit.jpg" },
  { id: 6,  name: "Cardigan Panjang", category: "Outerwear", price: 120000, img: "Cardigan Panjang.jpg" },
  { id: 7,  name: "Celana Chino", category: "Bawahan", price: 110000, img: "Celana Chino.webp" },
  { id: 8,  name: "Celana Formal", category: "Bawahan", price: 110000, img: "Celana Formal.webp" },
  { id: 9,  name: "Celana Jeans", category: "Bawahan", price: 110000, img: "Celana Jeans.webp" },
  { id: 10, name: "Celana Jogger Cargo", category: "Bawahan", price: 110000, img: "Celana Jogger Cargo.webp" },
  { id: 11, name: "Celana Kulot", category: "Bawahan", price: 110000, img: "Celana Kulot.jpg" },
  { id: 12, name: "Celana Palazzo", category: "Bawahan", price: 110000, img: "Celana Palazzo" },
  { id: 13, name: "Celana Training", category: "Bawahan", price: 110000, img: "Celana Training.webp" },
  { id: 14, name: "Cincin Silver", category: "Aksesori", price: 90000, img: "Cincin Silver.webp" },
  { id: 15, name: "Crop Tee", category: "Atasan", price: 100000, img: "Crop Tee.jpg" },
  { id: 16, name: "Culottes", category: "Bawahan", price: 110000, img: "Culottes.jpg" },
  { id: 17, name: "Dompet Kulit", category: "Aksesori", price: 90000, img: "Dompet Kulit" },
  { id: 18, name: "Espadrilles", category: "Footwear", price: 130000, img: "Espadrilles" },
  { id: 19, name: "Gelang Kulit", category: "Aksesori", price: 90000, img: "Gelang Kulit.jpg" },
  { id: 20, name: "High Heels", category: "Footwear", price: 130000, img: "High Heels.webp" },
  { id: 21, name: "Hijab Voal", category: "Aksesori", price: 90000, img: "Hijab Voal.png" },
  { id: 22, name: "Ikat Pinggang Kulit", category: "Aksesori", price: 90000, img: "Ikat Pinggang Kulit.jpg" },
  { id: 23, name: "Jaket Denim", category: "Outerwear", price: 120000, img: "Jaket Denim.jpg" },
  { id: 24, name: "Jaket Kulit", category: "Outerwear", price: 120000, img: "Jaket Kulit.jpg" },
  { id: 25, name: "Jaket Parasut", category: "Outerwear", price: 120000, img: "Jaket Parasut.webp" },
  { id: 26, name: "Jaket Varsity", category: "Outerwear", price: 120000, img: "Jaket Varsity.jpg" },
  { id: 27, name: "Jam Tangan Casual", category: "Aksesori", price: 90000, img: "Jam Tangan Casual.png" },
  { id: 28, name: "Jogger Pants", category: "Bawahan", price: 110000, img: "Jogger Pants" },
  { id: 29, name: "Kacamata Fashion", category: "Aksesori", price: 90000, img: "Kacamata Fashion.jpg" },
  { id: 30, name: "Kalung Layer", category: "Aksesori", price: 90000, img: "Kalung Layer.jpg" },
  { id: 31, name: "Kaos Polo", category: "Atasan", price: 100000, img: "Kaos Polo" },
  { id: 32, name: "Kaos Polos", category: "Atasan", price: 100000, img: "Kaos Polos.jpg" },
  { id: 33, name: "Kemeja Flanel", category: "Atasan", price: 100000, img: "Kemeja Flanel.webp" },
  { id: 34, name: "Kipas Tangan", category: "Aksesori", price: 90000, img: "Kipas Tangan.jpg" },
  { id: 35, name: "Legging Polos", category: "Bawahan", price: 110000, img: "Legging Polos.jpg" },
  { id: 36, name: "Legging Sport", category: "Bawahan", price: 110000, img: "Legging Sport.jpg" },
  { id: 37, name: "Loafers Pria", category: "Footwear", price: 130000, img: "Loafers Pria.webp" },
  { id: 38, name: "Long T-Shirt", category: "Atasan", price: 100000, img: "Long T-Shirt.webp" },
  { id: 39, name: "Mantel Musim Dingin", category: "Outerwear", price: 120000, img: "Mantel Musim Dingin.jpg" },
  { id: 40, name: "Outer Kimono", category: "Atasan", price: 100000, img: "Outer Kimono.jpg" },
  { id: 41, name: "Parka Hoodie", category: "Outerwear", price: 120000, img: "Parka Hoodie.jpg" },
  { id: 42, name: "Rok Plisket", category: "Bawahan", price: 110000, img: "Rok Plisket.jpg" },
  { id: 43, name: "Rompi Kasual", category: "Outerwear", price: 120000, img: "Rompi Kasual.jpg" },
  { id: 44, name: "Sandal Flat", category: "Footwear", price: 130000, img: "Sandal Flat.jpg" },
  { id: 45, name: "Sandal Jepit", category: "Footwear", price: 130000, img: "Sandal Jepit" },
  { id: 46, name: "Scarf Polos", category: "Aksesori", price: 90000, img: "Scarf Polos.jpg" },
  { id: 47, name: "Sepatu Formal", category: "Footwear", price: 130000, img: "Sepatu Formal.webp" },
  { id: 48, name: "Sepatu Platform", category: "Footwear", price: 130000, img: "Sepatu Platform.webp" },
  { id: 49, name: "Sepatu Running", category: "Footwear", price: 130000, img: "Sepatu Running.jpg" },
  { id: 50, name: "Shirt Dress", category: "Atasan", price: 100000, img: "Shirt Dress.jpg" },
  { id: 51, name: "Shorts Denim", category: "Bawahan", price: 110000, img: "Shorts Denim.jpg" },
  { id: 52, name: "Skirt A-Line", category: "Bawahan", price: 110000, img: "Skirt A-Line.jpg" },
  { id: 53, name: "Slip On Casual", category: "Footwear", price: 130000, img: "Slip On Casual.webp" },
  { id: 54, name: "Slip On Wanita", category: "Footwear", price: 130000, img: "Slip On Wanita.jpg" },
  { id: 55, name: "Sneakers Canvas", category: "Footwear", price: 130000, img: "Sneakers Canvas.jpg" },
  { id: 56, name: "Sweater Hoodie", category: "Outerwear", price: 120000, img: "Sweater Hoodie.webp" },
  { id: 57, name: "Sweater Rajut", category: "Atasan", price: 100000, img: "Sweater Rajut.jpg" },
  { id: 58, name: "Tank Top", category: "Atasan", price: 100000, img: "T-shirt Graphic.jpg" },
  { id: 59, name: "Tas Mini Backpack", category: "Aksesori", price: 90000, img: "T-shirt Oversize.jpg" },
  { id: 60, name: "Topi Bucket", category: "Aksesori", price: 90000, img: "Tank Top.png" },
  { id: 61, name: "Trench Coat", category: "Outerwear", price: 120000, img: "Tas Mini Backpack.jpg" },
  { id: 62, name: "T-shirt Graphic", category: "Atasan", price: 100000, img: "Topi Bucket" },
  { id: 63, name: "T-shirt Oversize", category: "Atasan", price: 100000, img: "Trench Coat" },
  { id: 64, name: "Tunik Motif", category: "Atasan", price: 100000, img: "Tunik Motif.jpg" },
  { id: 65, name: "Tunik Muslim", category: "Atasan", price: 100000, img: "Tunik Muslim.jpg" },
  { id: 66, name: "Vest Rajut", category: "Outerwear", price: 120000, img: "Vest Rajut" },
  { id: 67, name: "Wedges", category: "Footwear", price: 130000, img: "Wedges.png" },
  { id: 68, name: "Windbreaker", category: "Outerwear", price: 120000, img: "Windbreaker.jpg" },
];

export default products;
